model_name = "Nome:"
release_date = "Lançamento:"
release_date_not_found = "—"
release_date_future = "futuro"
license = "Licença:"
license_not_found = "—"
license_proprietary = "proprietária"
size = "Tamanho:"
size_not_found = "—"
base_model = "Modelo-base:"
base_model_not_found = "—"
knowledge_cutoff = "Data de corte dos dados:"
knowledge_cutoff_not_found = "—"
knowledge_cutoff_possibly_earlier = "ou anterior"
knowledge_cutoff_possibly_later = "ou posterior"
origin = "Equipe:"
training_data = "Dados de treinamento:"
training_data_not_found = "—"
language_variety = "Variante do idioma:"
language_varieties = "Variantes do idioma:"
language_varieties_not_found = "—"
model_id = "ID do modelo:"
model_id_not_found = "—"
weight_availability = "Disponibilidade dos pesos:"
weight_availability_pending = "pendente"
weight_availability_yes = "sim"
weight_availability_no = "não"
public_api_availability = "API associada:"
public_api_availability_pending = "pendente"
public_api_availability_yes = "sim"
public_api_availability_no = "não"
online_chat_availability = "Chat online:"
online_chat_availability_pending = "pendente"
online_chat_availability_yes = "sim"
online_chat_availability_no = "não"

contributors = "Contribuidores:"

[language_names]
pt-BR = "português brasileiro"
pt-PT = "português europeu"
gl-ES = "galego"
