model_name = "Name:"
release_date = "Release date:"
release_date_not_found = "—"
release_date_future = "future"
license = "License:"
license_not_found = "—"
license_proprietary = "proprietary"
size = "Size:"
size_not_found = "—"
base_model = "Base model:"
base_model_not_found = "—"
knowledge_cutoff = "Knowledge cutoff date:"
knowledge_cutoff_not_found = "—"
knowledge_cutoff_possibly_earlier = "or earlier"
knowledge_cutoff_possibly_later = "or later"
origin = "Team:"
training_data = "Training data:"
training_data_not_found = "—"
language_variety = "Language variety:"
language_varieties = "Language varieties:"
language_varieties_not_found = "—"
model_id = "Model ID:"
model_id_not_found = "—"
weight_availability = "Weight availability:"
weight_availability_pending = "pending"
weight_availability_yes = "yes"
weight_availability_no = "no"
public_api_availability = "Associated API:"
public_api_availability_pending = "pending"
public_api_availability_yes = "yes"
public_api_availability_no = "no"
online_chat_availability = "Online chat:"
online_chat_availability_pending = "pending"
online_chat_availability_yes = "yes"
online_chat_availability_no = "no"

contributors = "Contribuitors:"

[language_names]
pt-BR = "Brazilian Portuguese"
pt-PT = "European Portuguese"
gl-ES = "Galician"
